/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package deviceloanapp;

import javax.swing.table.DefaultTableModel;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author CelinaMoali
 */
public class DeviceLoanGUI extends javax.swing.JFrame {
    
    //main data structures used by gui
    private DeviceLinkedList deviceList = new DeviceLinkedList(); //stores all active loans
    private RequestQueue requestQueue = new RequestQueue(); // stores all awaiting requests
    private ReturnStack returnStack = new ReturnStack(); //stores recently returned devices
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DeviceLoanGUI.class.getName());

    /**
     * Creates new form DeviceLoanGUI
     */
    
    //constructor creating the form and set up the tables
    public DeviceLoanGUI() {
        initComponents();
        setTables();
    }
    
    //sets column headings for each jtable, making sure the tables start with the correct
    // structure
    private void setTables() {
    DeviceListTable.setModel(new javax.swing.table.DefaultTableModel(
        new Object[][]{},
        new String[]{"Device ID", "User ID", "First Name", "Last Name", "Due Date"}
    ));

    QueueTable.setModel(new javax.swing.table.DefaultTableModel(
        new Object[][]{},
        new String[]{"Awaiting Device ID"}
    ));

    StackTable.setModel(new javax.swing.table.DefaultTableModel(
        new Object[][]{},
        new String[]{"Returned Device ID"}
    ));
}
    
    //reloads the three tables from current data structures
    private void refreshTables() {
        DefaultTableModel deviceModel = (javax.swing.table.DefaultTableModel) DeviceListTable.getModel();
        DefaultTableModel queueModel = (javax.swing.table.DefaultTableModel) QueueTable.getModel();
        DefaultTableModel stackModel = (javax.swing.table.DefaultTableModel) StackTable.getModel();
        
        //clear all old rows before adding updated ones
        deviceModel.setRowCount(0);
        queueModel.setRowCount(0);
        stackModel.setRowCount(0);
        
        //loop through linked list, adding each devide to main table
        Node temp = deviceList.getHead();
        while (temp != null) {
            Device d = temp.data;
            deviceModel.addRow(new Object[]{
                d.getDeviceID(),
                d.getUserID(),
                jTextField1.getText(),
                jTextField2.getText(),
                d.getDueDate()
            });
        temp = temp.next;
    }
    
    //loop through queue and display awaiting requests
    temp = requestQueue.getFront();
    while (temp != null) {
        queueModel.addRow(new Object[]{temp.data.getDeviceID()});
        temp = temp.next;
    }
    
    //loop through stack and display returned devices
    temp = returnStack.getTop();
    while (temp != null) {
        stackModel.addRow(new Object[]{temp.data.getDeviceID()});
        temp = temp.next;
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        AddDeviceBtn = new java.awt.Button();
        ReturnBtn = new java.awt.Button();
        ExtendBtn = new java.awt.Button();
        jScrollPane2 = new javax.swing.JScrollPane();
        DeviceListTable = new javax.swing.JTable();
        jOptionPane1 = new javax.swing.JOptionPane();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        StackTable = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        QueueTable = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Device Loan System");

        jLabel2.setText("First name:");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel3.setText("Last name:");

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jLabel4.setText("Phone No.:");

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        jLabel5.setText("Address:");

        jLabel6.setText("User ID:");

        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });

        jLabel7.setText("Device ID:");

        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });

        AddDeviceBtn.setLabel("Add Device");
        AddDeviceBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddDeviceBtnActionPerformed(evt);
            }
        });

        ReturnBtn.setLabel("Returned");
        ReturnBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReturnBtnActionPerformed(evt);
            }
        });

        ExtendBtn.setLabel("Extend Loan");
        ExtendBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExtendBtnActionPerformed(evt);
            }
        });

        DeviceListTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(DeviceListTable);

        jLabel9.setText("Device List:");

        StackTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(StackTable);

        QueueTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(QueueTable);

        jLabel10.setText("Awaiting requests:");

        jLabel11.setText("Recent returns:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(189, 189, 189)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel10))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel11)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel8)
                                    .addGap(36, 36, 36)
                                    .addComponent(AddDeviceBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(63, 63, 63)
                                    .addComponent(ReturnBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(70, 70, 70)
                                    .addComponent(ExtendBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(22, 22, 22))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel8))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ExtendBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ReturnBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AddDeviceBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(30, 30, 30)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(jLabel10))
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed
    
    
    //adds a new device loan into the system, reading the text field values,
    //creating a user and a device. adds device to linked list and queue, then refreshes tables
    private void AddDeviceBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddDeviceBtnActionPerformed
        String firstName = jTextField1.getText();
        String lastName = jTextField2.getText();
        String phone = jTextField3.getText();
        String address = jTextField4.getText();
        String userID = jTextField5.getText();
        String deviceID = jTextField6.getText();

        //validation to ensre no field is left blank
        if(firstName.isEmpty() || lastName.isEmpty() || phone.isEmpty() || address.isEmpty() || userID.isEmpty() || deviceID.isEmpty()){
            JOptionPane.showMessageDialog(this, "please fill in all fields.");
            return;
        }
        
        //phone number must be 10 digits
        if(phone.length() != 10){
            JOptionPane.showMessageDialog(this, "phone number must be 10 digits.");
            return;
        }

        //checks each character in phone number is a digit
        for(int i = 0; i < phone.length(); i++){
            if(!Character.isDigit(phone.charAt(i))){
                JOptionPane.showMessageDialog(this, "phone number must only contain numbers.");
                return;
            }
        }

        //user id must be 7 digits
        if(userID.length() != 7){
            JOptionPane.showMessageDialog(this, "user id must be 7 digits.");
            return;
        }

        //checks each character in user id is a digit
        for(int i = 0; i < userID.length(); i++){
            if(!Character.isDigit(userID.charAt(i))){
                JOptionPane.showMessageDialog(this, "user id must only contain numbers.");
                return;
            }
        }
        
        //device id must be 1 letter + 5 digits
        if(deviceID.length() != 6){
            JOptionPane.showMessageDialog(this, "device id must be 6 characters long.");
            return;
        }

        //first character must be T or L
        char first = deviceID.charAt(0);
        if(first != 'T' && first != 'L'){
            JOptionPane.showMessageDialog(this, "device id must start with T or L.");
            return;
        }

        //last 5 characters must all be digits
        for(int i = 1; i < deviceID.length(); i++){
            if(!Character.isDigit(deviceID.charAt(i))){
                JOptionPane.showMessageDialog(this, "last 5 characters of device id must be numbers.");
                return;
            }
        }
        //checks if device id already exists
        if(deviceList.search(deviceID) != null){
            JOptionPane.showMessageDialog(this, "device id already exists.");
            return;
        }
        //crete a new user object from entered details
        User user = new User(userID, firstName, lastName, phone, address);
        
        //sets a due date 30 days from today
        Calendar cal = java.util.Calendar.getInstance();
        cal.add(Calendar.DAY_OF_MONTH, 30);
        Date dueDate = cal.getTime();

        Device device;
        
        //if id starts with L, make a laptop object
        //otherwise make a tablet object
        if(deviceID.toUpperCase().startsWith("L")){
            device = new Laptop(deviceID, user.getUserID(), dueDate, "Windows");
        } 
        else{
            device = new Tablet(deviceID, user.getUserID(), dueDate, "iPad");
        }
        
        //stores the device in main linked list, also placing it in request queue
        deviceList.add(device);
        requestQueue.enqueue(device);

        //refresh the gui to show new data
        refreshTables();

        JOptionPane.showMessageDialog(this, "device added successfully.");

        jTextField1.setText("");
        jTextField2.setText("");
        jTextField3.setText("");
        jTextField4.setText("");
        jTextField5.setText("");
        jTextField6.setText("");
    }//GEN-LAST:event_AddDeviceBtnActionPerformed
    
    //returning devices, searching for devices, removing it from linked list
    // pushingit to return stack
    private void ReturnBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReturnBtnActionPerformed
        String deviceID = jTextField6.getText();
        if(deviceID.isEmpty()){
            JOptionPane.showMessageDialog(this, "enter a device id.");
            return;
        }
        
        //device id must be 1 letter + 5 digits
        if(deviceID.length() != 6){
            JOptionPane.showMessageDialog(this, "device id must be 6 characters long.");
            return;
        }

        //first character must be T or L
        char first = deviceID.charAt(0);
        if(first != 'T' && first != 'L'){
            JOptionPane.showMessageDialog(this, "device id must start with T or L.");
            return;
        }

        //last 5 characters must all be digits
        for(int i = 1; i < deviceID.length(); i++){
            if(!Character.isDigit(deviceID.charAt(i))){
                JOptionPane.showMessageDialog(this, "last 5 characters of device id must be numbers.");
                return;
            }
        }
        //search for the device in active loans
        Device d = deviceList.search(deviceID);

        if(d == null){
            JOptionPane.showMessageDialog(this, "device not found.");
            return;
        }
        
        //add the returned devices to return stalk
        returnStack.push(d);
        
        //remove the devices from the active loan list
        deviceList.remove(deviceID);
        
        //removing the device form awaiting queue too
        requestQueue.removeByDeviceID(deviceID);
        
        refreshTables();
        JOptionPane.showMessageDialog(this, "device returned successfully.");

    }//GEN-LAST:event_ReturnBtnActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed
    
    //extends due date of existing loan, finding matching device and adds 
    //another 30 days to its due daye
    private void ExtendBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExtendBtnActionPerformed
        String deviceID = jTextField6.getText();
        if(deviceID.isEmpty()){
            JOptionPane.showMessageDialog(this, "enter a device id.");
            return;
        }      
        //device id must be 1 letter + 5 digits
        if(deviceID.length() != 6){
            javax.swing.JOptionPane.showMessageDialog(this, "device id must be 6 characters long.");
            return;
        }
        //first character must be T or L
        char first = deviceID.charAt(0);
        if(first != 'T' && first != 'L'){
            javax.swing.JOptionPane.showMessageDialog(this, "device id must start with T or L.");
            return;
        }
        //last 5 characters must all be digits
        for(int i = 1; i < deviceID.length(); i++){
            if(!Character.isDigit(deviceID.charAt(i))){
                javax.swing.JOptionPane.showMessageDialog(this, "last 5 characters of device id must be numbers.");
                return;
            }
        }
        //search for the device first
        Device d = deviceList.search(deviceID);
        if(d == null){
            javax.swing.JOptionPane.showMessageDialog(this, "device not found.");
            return;
        }        
        //update the due date by adding another 30 days
        Calendar cal = java.util.Calendar.getInstance();
        cal.setTime(d.getDueDate());
        cal.add(java.util.Calendar.DAY_OF_MONTH, 30);
        d.setDueDate(cal.getTime());
        refreshTables();
        JOptionPane.showMessageDialog(this, "loan extended by 30 days.");
    }//GEN-LAST:event_ExtendBtnActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new DeviceLoanGUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button AddDeviceBtn;
    private javax.swing.JTable DeviceListTable;
    private java.awt.Button ExtendBtn;
    private javax.swing.JTable QueueTable;
    private java.awt.Button ReturnBtn;
    private javax.swing.JTable StackTable;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JOptionPane jOptionPane1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    // End of variables declaration//GEN-END:variables
}
